MobulaFi/mobula-ui

src/features/user/portfolio/components/holdings/chart.tsx, src/features/user/portfolio/index.tsx
Fix:
- Glitch UI while changing portfolio 
- No chart visible on first render while changing portfolio 
Feature: 
- Skeleton loader for Holdings chart
Style: 
- Min height for Holding chart component
=> Fix: Portfolio glitch UI 

src/features/data/top100/components/box-right/AI-news/index.tsx, src/features/user/portfolio/components/holdings/chart.tsx
Fix:
- Glitch UI while changing portfolio
- No chart visible on first render while changing portfolio
Feature:
- Skeleton loader for Holdings chart
Style:
- Min height for Holding chart component
=> Fix: Portfolio glitch UI

src/app/portfolio/page.tsx, src/app/wallet/[address]/page.tsx, src/components/link.tsx, src/features/dao/protocol/components/ui/sorts/popup-community/index.tsx, src/features/user/portfolio/index.tsx
Fix: 
- DAO Protocol link didn't redirect
- Portfolio Props typescript error
Feature: 
- Generate dynamic metadata for wallet explorer
Style:
- DAO Protocol truncate social links and add margin
=> Fix: DAO Protocol social link redirection

src/features/user/portfolio/components/category/activity/index.tsx, src/features/user/portfolio/components/category/cryptocurrencies/transaction/index.tsx, src/features/user/portfolio/components/pnl/index.tsx, src/features/user/portfolio/components/ui/category-switcher/index.tsx, src/features/user/portfolio/components/ui/tbody-skeleton/index.tsx, src/features/user/portfolio/index.tsx, tailwind.config.js
Fix: 
- Portfolio glitch UI while searching unknown wallet
- Activity loader skeleton rendering on each click on Activity section
- Activity transactions mixed with crypto table transaction
Feature: 
- Adding animation for refresh icon & replace icon
Style:
- Activity image skeleton margin
=> Fix: Portfolio glitch UI while searching unknown wallet

src/app/page.tsx, src/features/data/top100/components/box-right/AI-news/index.tsx, src/features/data/top100/context-manager/index.tsx, src/interfaces/pages/top100.tsx, src/layouts/footer/constant.tsx
Fix:
- News was 8 days old, remove the fetch function from SSR
Feature:
- Adding Blog link into footer
=> Fix: Resolve issue with news 

src/features/data/top100/components/box-middle/btc-dominance/index.tsx, src/features/data/top100/components/box-right/AI-news/index.tsx, src/interfaces/assets.tsx, src/layouts/header-banner/index.tsx, src/lib/echart/line/index.tsx, src/lib/echart/line/useDefault.tsx
Feature:
- Adding triangle for up/down token mentioned in the news
- Redirect link onClick token mentioned
Fix: 
- Chart tooltip for BTC Dominance
- Background for charts depending on colorMode
=> Fix: reported issues

src/features/data/top100/components/box-right/AI-news/index.tsx, src/features/data/top100/components/portfolio/index.tsx, src/features/user/portfolio/components/category/cryptocurrencies/index.tsx, src/features/user/portfolio/components/category/nfts/card.tsx, src/features/user/portfolio/components/category/nfts/index.tsx, src/features/user/portfolio/components/header/index.tsx, src/features/user/portfolio/components/popup/manage/edit.tsx, src/features/user/portfolio/components/ui/category-switcher/index.tsx, src/features/user/portfolio/hooks/index.tsx, src/features/user/portfolio/index.tsx, src/features/user/portfolio/main.tsx, src/hooks/holdings.tsx, src/lib/echart/line/useDefault.tsx
Feature:
- Possibility to hide token <0.01$ balance 
- NFT improvement responsive & UI
- NFT flow hide / restore / select 
- Hide asset UI & UX Improvement 
Fix: 
- Rotate triangle down icon on News
- Portfolio name replaced with address glitch
- NaN return on chart
Chore: 
- Remove logs
=> Feature: Improvement flow & UI on portfolio

src/features/asset/components/ui/popup-actors/index.tsx, src/features/user/portfolio/components/category/nfts/index.tsx, src/features/user/portfolio/components/ui/category-switcher/index.tsx
Fix:
- Crash on Nfts section ( portfolio )
- Popup core actor min height
=> Fix: Crash on NFTs

src/app/movers/page.tsx, src/features/data/movers/components/table-mover/index.tsx, src/features/data/movers/components/tbody/index.tsx, src/features/data/movers/index.tsx, src/layouts/header/components/chains-changer/index.tsx, src/layouts/header/components/user-section/index.tsx, src/popup/telegram-connect/index.tsx, src/utils/stream-movers.tsx
Feature: 
- Market metrics + ISR on Movers
Fix: 
- Remove telegram connector from header ( user section ) 
- Handle image for chain not supported on header
=> Feature: Market metrics + ISR on Mover

src/features/misc/listing-form/components/basic-information/index.tsx, src/features/misc/listing-form/components/contract-information/index.tsx, src/features/misc/listing-form/components/sales/index.tsx, src/features/misc/listing-form/components/submit/index.tsx, src/features/misc/listing-form/components/ui/inputs-template/index.tsx, src/features/misc/listing-form/context-manager/index.tsx, src/features/misc/listing-form/index.tsx, src/features/misc/listing-form/models.tsx, src/features/misc/listing-form/utils.tsx
For the new listing system we have in 
/Users/root69/mobula-ui/src/features/misc/listing-form/index.tsx
a function which will call an endpoint on the backend "/asset/listing-status", this endpoint will return a wallet which we put in the state of the listing useContext which I added "setWallet(response.data.wallet.address)", we will return this wallet to the user in 
/Users/root69/mobula-ui/src/features/misc/listing-form/components/submit/index.tsx
at the same time, we'll also call another backend endpoint with this wallet as a parameter in order to get the listing status, basically whether the wallet has balance or not (not a great idea, we'll have to see about changing this in the future). As soon as it receives balance, it'll update the new state that I've also created …
=> fix: new listing form

src/components/collapse.tsx, src/features/asset/components/widgets/essentials/charts/header.tsx, src/features/asset/components/widgets/essentials/index.tsx, src/features/misc/swap/index.tsx, src/hooks/chart-pref.tsx, src/layouts/swap/hooks/useSwapAssets.ts, src/layouts/swap/popup/select/index.tsx, src/layouts/swap/swap-variant/basic-swap.tsx, src/layouts/swap/utils.tsx
Feature: 
- Swap new version with Routers
- Custom hook for chart user preference
=> Feature: Swap new version

src/layouts/swap/swap-variant/basic-swap.tsx, src/lib/trading-view/models.tsx
Fix:
- TV chart default timeframe
- Swap mobile version width
=> Fix: Swap mobile version 

src/features/asset/components/widgets/essentials/index.tsx, src/features/asset/components/widgets/fundraising/index.tsx, src/features/asset/components/widgets/fundraising/rounds/index.tsx, src/features/asset/components/widgets/market/index.tsx, src/features/asset/components/widgets/vesting/index.tsx, src/features/asset/index.tsx, src/layouts/swap/common/popup/settings/components/small-swap-line/index.tsx, src/layouts/swap/swap-variant/basic-swap.tsx, src/layouts/swap/swap-variant/small-swap.tsx
Fix: 
- Swap arrow didn't work
- UI issue on fundraising section 
- Max width for asset page
- Improve flow on Swap asset page
=> Fix: Swap issues

package-lock.json, package.json, src/app/pair/[pair]/page.tsx, src/features/asset/components/pairs-selector/index.tsx, src/features/asset/components/token-main-info/index.tsx, src/features/asset/components/ui/ath-atl/index.tsx, src/features/asset/components/ui/similar-asset-template/index.tsx, src/features/asset/components/widgets/essentials/index.tsx, src/features/asset/components/widgets/essentials/trades/index.tsx, src/features/asset/index.tsx, src/features/data/top100/index.tsx, src/hooks/network.tsx, src/layouts/header/components/chains-changer/index.tsx, src/layouts/header/components/user-section/index.tsx, src/layouts/layout/index.tsx, src/layouts/swap/hooks/useButtonClick.ts, src/layouts/swap/hooks/useButtonStatus.ts, src/layouts/swap/index.tsx, src/layouts/swap/swap-variant/basic-swap.tsx, src/lib/echart/line/useDefault.tsx, src/lib/trading-view/utils/index.ts, src/popup/searchbar/components/result-pair/index.tsx, src/popup/switch-network/index.tsx, yarn.lock
Fix: 
- Infinite scroll on top 100 wasn't working du to recent change
- Header space on asset page
- Remove from SSR fetch for trades & social links
- Similar asset non clickable on asset page
- Remove BreadCrumb on asset page
- Swap working only for Ethereum chain
- Switch network popup
- Chart number formatted
- Remove Sub for main Asset price
- Handle no image for asset page
- ATH & ATL wasn't working anymore
=> Fix: issues reported

src/features/misc/listing-form/components/ui/multi-input-template/index.tsx, src/layouts/swap/utils.tsx
Fix to fetch contracts when a non-EVM token tries to list itself (currently no contracts are returned)
=> fix: listing nonEVM assets

src/features/misc/listing-form/components/ui/multi-input-template/index.tsx
fix: listing form contracts application error
=> fix: listing form contracts application error

src/app/new/page.tsx, src/components/load-more.tsx, src/features/analytic/components/popup/selector.tsx, src/features/asset/components/token-main-info/index.tsx, src/features/asset/components/widgets/essentials/token-metrics/index.tsx, src/features/asset/components/widgets/market/trading-pair/index.tsx, src/features/asset/index.tsx, src/features/data/chains/components/table-row/index.tsx, src/features/data/top100/components/table-body/index.tsx, src/features/data/top100/index.tsx, src/features/landings/home/components/curated-dataset/index.tsx, src/features/landings/home/components/ui/title/index.tsx, src/features/landings/home/index.tsx, src/features/landings/template/constants.tsx, src/features/misc/listing-form/components/submit/index.tsx, src/features/misc/listing-form/components/ui/multi-input-template/index.tsx, src/features/user/portfolio/components/category/activity/index.tsx, src/features/user/portfolio/components/category/nfts/index.tsx, src/features/user/portfolio/context-manager/index.tsx, src/features/user/portfolio/index.tsx, src/features/user/portfolio/models.tsx, src/hooks/holdings.tsx, src/layouts/header/components/mobile/index.tsx, src/lib/echart/basic-line/index.tsx, src/popup/searchbar/components/result-ens/index.tsx, src/popup/searchbar/components/result-pair/index.tsx, src/popup/searchbar/core.tsx, src/utils/stream-chains.tsx
Feature: 
- Adding rank on asset page
Fix: 
- Menu mobile Swap link position
- Price update asset page
- Activity not updating while changing wallet to track
- leading height & text balance on landing
- fetch asset on scroll top100
=> Fix: Multi issues

src/features/dao/protocol/components/sorts/index.tsx, src/features/dao/protocol/components/ui/sorts/change-template/index.tsx, src/features/misc/listing-form/components/submit/index.tsx
- remove useless data on protocol page edit request (edits, protocol_id)
- fix format of links & team display on protocol page edit request
- fix tokenomics display crash
- setup cooldown edit request ui
=> Fix/edit request UI

src/features/asset/components/token-social-info/index.tsx
- adding back "edit page" button and "edit system" in same time
=> adding back "edit page" button and "edit system" in same time

src/features/asset/components/widgets/vesting/next-unlock-event/index.tsx
=> fix next vesting
